Fix Jest error when spying on import
TypeError: Cannot set property expand of #<Object> which has only a
getter

Avoid import of re-exported module.  Add new test suite for external
exports.