Fix TypeScript error accessing window.Worker
error TS2339: Property 'Worker' does not exist on type 'Window'.

Refactor feature detection added in 92b3126.