Enable esModuleInterop flag
Fix errors during tests:
 - TypeError: escape_string_regexp_1.default is not a function
 - TypeError: shuffle_array_1.default is not a function

Remove allowSyntheticDefaultImports flag since it's a subset of the
esModuleInterop flag.